version: '3.3'
services:
    mondu-node:
        container_name: mondu-node
        build:
          context: .
          dockerfile: Dockerfile
        restart: unless-stopped
        ports:
          - 3000:3000
